---
- name: Install cron job.
  cron:
    special_time: hourly
    name: pull
    job: ansible-pull -U https://github.com/toomyem/ansible -i $(hostname -s), -o -s 45 2>&1 >/var/log/pull.log
    state: present

- name: Install basic packages
  apt:
    name:
      - htop
      - vim
      - gnupg2
      - curl
      - sudo
    state: present

- name: Setup aliases
  lineinfile:
    path: /root/.bashrc
    line: alias ll='ls -lh'
    regexp: ^alias ll=
    state: present

- name: Set local timezone
  file:
    path: /etc/localtime
    src: /usr/share/zoneinfo/Europe/Warsaw
    state: link

